[package]
name = "zkp-circuit-practice-halo2"
version = "0.1.0"
edition = "2018"

[dependencies]
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "4283713ec76051eaf21a06d0279fa7d3497cafb6" }

[dev-dependencies]
enum-iterator = "0.6.0"
